spring:
  application:
    name: task_management

  datasource:
    url: jdbc:postgresql://localhost:5434/task_management
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
